import json
import shutil
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
from tqdm import tqdm

from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
from lerobot.common.datasets.utils import DEFAULT_FEATURES, serialize_dict

# --- Compatibility shims for the annotate env ---
# lerobot v0.1.0 was written for `datasets` 2.x, where `dataset[column]`
# returns a list of tensors. The annotate env ships `datasets` 5.x, where it
# returns a `Column` object, which breaks `torch.stack(hf_dataset["timestamp"])`
# inside `check_timestamps_sync`. That function is only a sanity check on
# timestamp spacing, so we neutralise it. We bind the no-op into both the
# `utils` module and the `lerobot_dataset` module (which imported it by name).
import lerobot.common.datasets.lerobot_dataset as _lr_ds_module  # noqa: E402
import lerobot.common.datasets.utils as _lr_utils  # noqa: E402
from lerobot.common.datasets.compute_stats import compute_stats as _orig_compute_stats  # noqa: E402


def _noop_check_timestamps_sync(*_args, **_kwargs) -> bool:
    return True


_lr_utils.check_timestamps_sync = _noop_check_timestamps_sync
_lr_ds_module.check_timestamps_sync = _noop_check_timestamps_sync


# Force single-process statistics computation. The annotate env's
# `multiprocess`/`datasets` combo emits ResourceTracker errors under worker
# processes; `num_workers=0` keeps `consolidate()` reliable (slower but safe).
def _compute_stats_singleproc(dataset, batch_size=8, num_workers=0, max_num_samples=None):
    return _orig_compute_stats(
        dataset, batch_size=batch_size, num_workers=0, max_num_samples=max_num_samples
    )


_lr_ds_module.compute_stats = _compute_stats_singleproc


def _get_task_time_ranges(ann_tasks: list[dict[str, Any]]) -> list[tuple[float, float]]:
    """Extract (start, end) time ranges from annotation tasks.

    Returns list of (start, end) tuples sorted by start time.
    """
    ranges = []
    for task in ann_tasks:
        start = task.get("start")
        end = task.get("end")
        if start is not None and end is not None and start < end:
            ranges.append((float(start), float(end)))
    return sorted(ranges, key=lambda x: x[0])


def process_dataset_with_annotations(
    dataset_root: Path,
    annotations: dict[int, Any],
    deleted_episodes: set[int],
    output_dir: Path,
    info: dict[str, Any],
    progress_callback: Callable[[dict[str, Any]], None] | None = None,
) -> dict[str, Any]:
    """Process a LeRobot dataset using the LeRobotDataset API.

    Loads the source dataset with `LeRobotDataset`, iterates over episodes,
    drops deleted episodes, trims remaining episodes to the annotated task
    time ranges, and writes the result into a fresh `LeRobotDataset`.

    The destination dataset is built through the `save_episode` / `consolidate`
    pipeline, so all LeRobot metadata (info.json, tasks.jsonl, episodes.jsonl,
    stats.json) is regenerated by the library itself.

    Args:
        dataset_root: Path to the original (v2.0) dataset root.
        annotations: Dict mapping episode_index to EpisodeAnnotations.
        deleted_episodes: Set of episode indices to delete entirely.
        output_dir: Path where the processed dataset will be saved.
        info: Original dataset info.json content (used for repo_id/fps fallback).

    Returns:
        Summary dict with statistics about the processed dataset.
    """
    dataset_root = Path(dataset_root)
    output_dir = Path(output_dir)

    def _emit(ev: dict[str, Any]) -> None:
        if progress_callback is not None:
            try:
                progress_callback(ev)
            except Exception:
                pass

    repo_id = info.get("repo_id") or "local_dataset"

    # Load source dataset (v2.0) directly from disk.
    _emit({"type": "phase", "phase": "loading"})
    print(f"[Process] Loading source LeRobotDataset from {dataset_root}")
    src = LeRobotDataset(
        repo_id=repo_id,
        root=dataset_root,
        local_files_only=True,
        download_videos=False,
    )

    fps = src.fps
    features = src.features
    use_videos = len(src.meta.video_keys) > 0
    original_episodes = src.meta.total_episodes

    # Features that must be provided per-frame (everything LeRobot does not
    # manage automatically).
    data_feature_keys = [k for k in features if k not in DEFAULT_FEATURES]

    _emit({"type": "phase", "phase": "processing", "total_episodes": original_episodes})

    # Create the destination dataset. LeRobotDataset.create requires a fresh,
    # non-existent root directory.
    if output_dir.exists():
        print(f"[Process] Removing existing output dir {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.parent.mkdir(parents=True, exist_ok=True)

    print(f"[Process] Creating destination LeRobotDataset at {output_dir}")
    dst = LeRobotDataset.create(
        repo_id=repo_id,
        fps=fps,
        root=output_dir,
        features=features,
        use_videos=use_videos,
    )

    # Timestamp column handle: per-frame trim check without reading full rows.
    ts_col = src.hf_dataset["timestamp"]

    tasks_set: set[str] = set()
    kept_episodes = 0
    total_frames = 0

    ep_pbar = tqdm(
        range(original_episodes),
        total=original_episodes,
        desc="Processing episodes",
        unit="ep",
        dynamic_ncols=True,
    )
    for ep_idx in ep_pbar:
        if ep_idx in deleted_episodes:
            ep_pbar.write(f"[Process] Skipping deleted episode {ep_idx}")
            _emit({"type": "episode_skip", "ep": int(ep_idx), "reason": "deleted", "total_kept": kept_episodes, "total_frames": total_frames})
            continue

        ann = annotations.get(int(ep_idx))
        ann_tasks = ann.tasks if ann and ann.tasks else []
        time_ranges = _get_task_time_ranges(ann_tasks)

        # v0.1.0 save_episode assigns a single task to the whole episode.
        # Prefer the first annotated task name; otherwise preserve the source
        # episode's task; otherwise fall back to a default label.
        episode_task: str | None = None
        if ann_tasks:
            episode_task = next((t["name"] for t in ann_tasks if t.get("name")), None)
        if episode_task is None:
            src_ep = src.meta.episodes[ep_idx] if ep_idx < len(src.meta.episodes) else {}
            src_tasks = src_ep.get("tasks", []) if isinstance(src_ep, dict) else []
            if isinstance(src_tasks, list) and src_tasks:
                episode_task = src_tasks[0]

        ep_from = int(src.episode_data_index["from"][ep_idx])
        ep_to = int(src.episode_data_index["to"][ep_idx])
        ep_len = ep_to - ep_from

        # Select kept frames using only their timestamps (no full-row reads
        # for skipped frames).
        kept_abs: list[int] = [
            abs_idx
            for abs_idx in range(ep_from, ep_to)
            if not time_ranges
            or any(s <= float(ts_col[abs_idx]) <= e for s, e in time_ranges)
        ]

        if not kept_abs:
            ep_pbar.write(f"[Process] Warning: Episode {ep_idx} empty after trimming, skipping")
            _emit({"type": "episode_skip", "ep": int(ep_idx), "reason": "empty", "total_kept": kept_episodes, "total_frames": total_frames})
            continue

        # Copy kept frames into the episode buffer directly (bypassing
        # add_frame). Image objects are embedded into the parquet by
        # _save_episode_table via datasets.Image -- no PNG round-trip.
        if dst.episode_buffer is None:
            dst.episode_buffer = dst.create_episode_buffer()
        buf = dst.episode_buffer
        added = 0
        frame_pbar = tqdm(kept_abs, desc=f"  Ep {ep_idx} frames", unit="frm",
                          leave=False, dynamic_ncols=True)
        for abs_idx in frame_pbar:
            row = src.hf_dataset[abs_idx]
            fi = buf["size"]
            buf["frame_index"].append(fi)
            buf["timestamp"].append(fi / fps)
            for key in data_feature_keys:
                if key in row:
                    buf[key].append(row[key])
            buf["size"] += 1
            added += 1
        frame_pbar.close()

        final_task = episode_task or "default"
        with tqdm.external_write_mode(ep_pbar):
            dst.save_episode(task=final_task, encode_videos=False)
        tasks_set.add(final_task)
        kept_episodes += 1
        total_frames += added
        ep_pbar.set_postfix(
            kept=kept_episodes, frames=total_frames, refresh=False
        )
        ep_pbar.write(
            f"[Process] Episode {ep_idx} -> new ep {kept_episodes - 1} "
            f"({added}/{ep_len} frames kept, task='{final_task}')"
        )
        _emit({
            "type": "episode_done",
            "ep": int(ep_idx),
            "new_ep": kept_episodes - 1,
            "kept": int(added),
            "ep_len": int(ep_len),
            "task": final_task,
            "total_kept": kept_episodes,
            "total_frames": total_frames,
        })
    ep_pbar.close()

    if kept_episodes == 0:
        raise RuntimeError("All episodes were deleted or resulted in empty data after trimming")

    # Consolidate: compute stats, write stats.json.
    _emit({"type": "phase", "phase": "consolidating"})
    print("[Process] Consolidating dataset (computing statistics)...")
    dst.consolidate(run_compute_stats=True, keep_image_files=False)
    print("[Process] Consolidation complete")

    task_names_sorted = sorted(tasks_set)
    summary = {
        "output_dir": str(output_dir),
        "total_episodes": kept_episodes,
        "total_frames": total_frames,
        "total_tasks": len(task_names_sorted),
        "tasks": task_names_sorted,
        "deleted_episodes": sorted(deleted_episodes),
        "original_episodes": original_episodes,
        "kept_episodes": kept_episodes,
    }

    print("[Process] Dataset processing complete!")
    print(f"  Original: {summary['original_episodes']} episodes")
    print(f"  Deleted: {len(deleted_episodes)} episodes")
    print(f"  Result: {kept_episodes} episodes, {total_frames} frames, {len(task_names_sorted)} tasks")
    return summary